services:
  telegram_bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - telegram_bot/.env
      - postgres/.env
      - redis/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4
    restart: unless-stopped
    env_file: postgres/.env
    expose:
      - 5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2
    restart: unless-stopped
    env_file: redis/.env
    expose:
      - 6379
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
    driver: local

  postgres_volume:
    driver: local
