from .account import AccountActions
from .accrual_of_points import AccrualOfPointsActions
from .admin import AdminActions
from .edit_shop import EditShopActions
from .event import EventActions
from .help import HelpActions
from .moderation import ModerationActions
from .promocode import PromocodeActions
from .purchases import PurchasesActions
from .registration import RegistrationsActions
from .admin_promocode import AdminPromocodeActions
from .grant_privileges import GrantPrivilegesActions
